Fix/add logging on secret cache
Trunkrs/common pull request #20
Opened 2022-01-19 14:16 UTC by nljms

## Notes
- [x] Added logging on `SecretsCache` and `GlobalAtomicCache`
- [x] Replaced `tokenCacheStoreName` as it fetches `appClientSecretName` on CacheStore

2022-01-19 14:20 UTC, fean requested changes

2022-01-19 14:28 UTC, nljms commented on providers/auth0.ts
> +        tokenCacheStoreName,
This is actually on the [MachineClient](https://github.com/Trunkrs/common/blob/f6d8819c3b9144a1e77c49ca0c701347db82e7e4/providers/auth0.ts#L57) part.

2022-01-19 14:30 UTC, nljms commented on providers/auth0.ts
> +        tokenCacheStoreName,
The `DailyTokenCache` retrieves the `appClientSecretName` instead of the `tokenCacheStoreName`

2022-01-19 14:36 UTC, fean commented on providers/auth0.ts
> +        tokenCacheStoreName,
Hmmm, I don't think [that is correct](https://github.com/Trunkrs/common/blob/f6d8819c3b9144a1e77c49ca0c701347db82e7e4/providers/auth0.ts#L34), it looks like it uses the `tokenCacheStoreName` for the param in SSM.

The `appClientSecretName` is the name of the secret in which the `AppClient` is stored 🙂

2022-01-19 15:18 UTC, nljms commented on providers/auth0.ts
> +        tokenCacheStoreName,
Yeah, but as you can see on the [MachineClient](https://github.com/Trunkrs/common/blob/f6d8819c3b9144a1e77c49ca0c701347db82e7e4/services/client/MachineClient.ts#L16) constructor, we are supposed to be having the `secretCacheKey` as a parameter for the Cache which is the [DailyTokenCache](https://github.com/Trunkrs/common/blob/f6d8819c3b9144a1e77c49ca0c701347db82e7e4/providers/auth0.ts#L34). When instantiating the [MachineClient](https://github.com/Trunkrs/common/blob/f6d8819c3b9144a1e77c49ca0c701347db82e7e4/providers/auth0.ts#L57) we are passing the `appClientSecretName` instead?

2022-01-19 15:22 UTC, nljms commented on providers/auth0.ts
> +        tokenCacheStoreName,
Or yeah maybe I'm wrong. I'll revert the code first then I'll be checking the logs

2022-01-20 10:59 UTC, fean requested changes

2022-01-20 10:59 UTC, fean commented on providers/auth0.ts
> +  )
This should be provided by the `utilsProvider` 🙂

2022-01-20 11:40 UTC, fean approved these changes
Thanks for the effort my man! 💪

2022-01-20 11:40 UTC, merged