improve batching behaviour for DynoDM
Trunkrs/common pull request #9
Opened 2021-11-08 14:10 UTC by lueue

2021-11-09 07:55 UTC, fean requested changes

2021-11-09 07:55 UTC, fean commented on services/aws/dynamodb/DynamoDataStorage.ts
> +        await this.documentClient
```suggestion
      if (page.Items?.length) {
```

2021-11-09 07:55 UTC, fean commented on services/aws/dynamodb/DynamoDataStorage.ts
> +        this.documentClient
Now what happens if there is a duplicate key inside one of the batches? 
Think of the following scenario: Three batches were written one batch failed due to a key constraint. 

How do you enforce that the data source is going to be consistent with the application state? 🙂

2021-11-09 10:13 UTC, lueue commented on services/aws/dynamodb/DynamoDataStorage.ts
> +        this.documentClient
I added success and failed states for the items to keep track of what is going on or which items failed. Then the implementor can decide what needs to happen

2021-11-09 10:25 UTC, fean requested changes

2021-11-09 10:25 UTC, fean commented on services/aws/dynamodb/DynamoDataStorage.ts
> +        failed.push(...batch)
Are you sure this is the right way to process those items?
 [Check out the documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#batchWrite-property) for `batchWrite`. In the returning object there is a property `UnprocessedItems`, now I don't know in which cases that property is used. So maybe you could look into that as well? 🙂

2021-11-10 13:36 UTC, fean commented
Awesome addition man! Looks good! 💪

2021-11-10 13:36 UTC, fean approved these changes

2021-11-10 13:36 UTC, merged